name: "CI Pipeline"

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches: [develop, master]

jobs:
  build:
    name: Linter and unit tests
    runs-on: ubuntu-latest
    steps:

      - name: Actions checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v1
        with:
          java-version: '8.x'

      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.4'
          channel: 'stable'

      - name: Flutter version
        run: flutter --version

      - name: Pub Get
        run: flutter pub get
      
      - name: Run linter
        run: flutter analyze
      
      # - name: Run test
      #   run: flutter test
